USE collegedb;
--WE WILL SEE SUBQUERIES,CORELATED SUBQUERIES AND VIEWS
--SUBQUERIES ARE ALTERNATIVE TO JOINS IN () LIES INNER QUERY WHICH IS EXECUTED FIRST AND OUTER QUERY DEPENDS ON THIS 
--Q1(Q2)

AND CORELATED SUBQUERY DEPEND ON OUTER QUERY FOR 1 OUTER QUERY INNER QUERY WILL EXECUTE ONCE IT IS SLOWER THAN JOINS

--VIEWS IN SQL IN A TEMP,VIRTUAL TABLE WHICH ONLY DISPLAYS FIELDS WHICH USER WANT AND CREATES 

CREATE VIEW info AS SELECT name,rollno FROM information;

SELECT * FROM info; 

--HERE WE COMPLETE BASIC MYSQL 